-- Tabele
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID DM_SHORT,
    CUSTOMER_NAME DM_NAME,
    BALANCE DM_AMOUNT,
    CURRENCY_ID DM_SHORT
);

CREATE TABLE ORDERS (
    ORDER_ID DM_SHORT,
    CUSTOMER_ID DM_SHORT,
    TOTAL DM_AMOUNT
);

